// <auto-generated />
using System;
using FastFoodOnline.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFood.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203021005_hihihaha")]
    partial class hihihaha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodOnline.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            Email = "admin@fastfood.local",
                            FullName = "Admin",
                            Password = "123456",
                            PhoneNumber = "0900000000",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "TP. Hồ Chí Minh",
                            Email = "customer@fastfood.local",
                            FullName = "Nguyễn Văn A",
                            Password = "123456",
                            PhoneNumber = "0911111111",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Burger bò phô mai, khoai tây chiên và Coca Cola",
                            ImageUrl = "https://burgerking.vn/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/1/7/17-whopper-b_-t_m-ph_-mai-c_-l_n.jpg",
                            IsActive = true,
                            Name = "Combo Burger Bò Đặc Biệt",
                            Price = 95000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "4 miếng gà rán, khoai tây chiên lớn và 2 Pepsi",
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=500",
                            IsActive = true,
                            Name = "Combo Gà Rán Gia Đình",
                            Price = 180000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Burger gà giòn, khoai tây chiên và nước cam ép",
                            ImageUrl = "https://images.unsplash.com/photo-1603064752734-4c48eff53d05?w=500",
                            IsActive = true,
                            Name = "Combo Burger Gà Tiết Kiệm",
                            Price = 100000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Burger bò nhỏ, cánh gà chiên và trà sữa",
                            ImageUrl = "https://images.unsplash.com/photo-1565299715199-866c917206bb?w=500",
                            IsActive = true,
                            Name = "Combo Học Sinh",
                            Price = 120000m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kem vani, bánh táo và trà sữa trân châu",
                            ImageUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500",
                            IsActive = true,
                            Name = "Combo Tráng Miệng Ngọt Ngào",
                            Price = 85000m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Burger bò bacon, khoai tây chiên và cà phê sữa",
                            ImageUrl = "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500",
                            IsActive = true,
                            Name = "Combo Burger Bacon Đặc Biệt",
                            Price = 128000m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Burger gà cay Hàn Quốc, cánh gà buffalo và trà sữa matcha",
                            ImageUrl = "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500",
                            IsActive = true,
                            Name = "Combo Gà Cay Hàn Quốc",
                            Price = 145000m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Salad caesar và sinh tố bơ",
                            ImageUrl = "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500",
                            IsActive = true,
                            Name = "Combo Healthy",
                            Price = 115000m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Gà nuggets, khoai tây chiên và nước cam ép",
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=500",
                            IsActive = true,
                            Name = "Combo Trẻ Em Vui Vẻ",
                            Price = 98000m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Burger phô mai nướng, hành tây chiên giòn và soda chanh dây",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsActive = true,
                            Name = "Combo Tiệc Nướng",
                            Price = 110000m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Burger gà giòn, bánh donut socola và cà phê đen",
                            ImageUrl = "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=500",
                            IsActive = true,
                            Name = "Combo Cà Phê Sáng",
                            Price = 95000m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Burger tôm, gỏi cuốn tôm",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsActive = true,
                            Name = "Combo Hải Sản Cao Cấp",
                            Price = 135000m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Gà rán phô mai, phô mai que chiên và trà sữa",
                            ImageUrl = "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500",
                            IsActive = true,
                            Name = "Combo Phô Mai Đặc Biệt",
                            Price = 130000m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Tiramisu, cheesecake dâu và trà đào cam sả",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500",
                            IsActive = true,
                            Name = "Combo Tráng Miệng Cao Cấp",
                            Price = 125000m
                        },
                        new
                        {
                            Id = 15,
                            Description = "2 burger bò phô mai, 2 khoai tây chiên và 2 pepsi",
                            ImageUrl = "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500",
                            IsActive = true,
                            Name = "Combo Bạn Bè",
                            Price = 225000m
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.ComboItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComboId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("FoodId");

                    b.ToTable("ComboItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComboId = 1,
                            FoodId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            ComboId = 1,
                            FoodId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            ComboId = 1,
                            FoodId = 7,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            ComboId = 2,
                            FoodId = 4,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            ComboId = 2,
                            FoodId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 6,
                            ComboId = 2,
                            FoodId = 8,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 7,
                            ComboId = 3,
                            FoodId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            ComboId = 3,
                            FoodId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            ComboId = 3,
                            FoodId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 10,
                            ComboId = 4,
                            FoodId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 11,
                            ComboId = 4,
                            FoodId = 6,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 12,
                            ComboId = 4,
                            FoodId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 13,
                            ComboId = 5,
                            FoodId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 14,
                            ComboId = 5,
                            FoodId = 14,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 15,
                            ComboId = 5,
                            FoodId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 16,
                            ComboId = 6,
                            FoodId = 36,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 17,
                            ComboId = 6,
                            FoodId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 18,
                            ComboId = 6,
                            FoodId = 26,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 19,
                            ComboId = 7,
                            FoodId = 37,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 20,
                            ComboId = 7,
                            FoodId = 40,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 21,
                            ComboId = 7,
                            FoodId = 42,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 22,
                            ComboId = 8,
                            FoodId = 30,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 24,
                            ComboId = 8,
                            FoodId = 24,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 25,
                            ComboId = 9,
                            FoodId = 41,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 26,
                            ComboId = 9,
                            FoodId = 11,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 27,
                            ComboId = 9,
                            FoodId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 28,
                            ComboId = 10,
                            FoodId = 38,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 29,
                            ComboId = 10,
                            FoodId = 48,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 30,
                            ComboId = 10,
                            FoodId = 44,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 31,
                            ComboId = 11,
                            FoodId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 32,
                            ComboId = 11,
                            FoodId = 51,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 33,
                            ComboId = 11,
                            FoodId = 25,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 34,
                            ComboId = 12,
                            FoodId = 15,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 35,
                            ComboId = 12,
                            FoodId = 29,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 37,
                            ComboId = 13,
                            FoodId = 39,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 38,
                            ComboId = 13,
                            FoodId = 49,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 39,
                            ComboId = 13,
                            FoodId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 40,
                            ComboId = 14,
                            FoodId = 52,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 42,
                            ComboId = 14,
                            FoodId = 23,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 43,
                            ComboId = 15,
                            FoodId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 45,
                            ComboId = 15,
                            FoodId = 11,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 46,
                            ComboId = 15,
                            FoodId = 8,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tag")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Burger bò 100% thịt thật với phô mai cheddar tan chảy, rau xà lách tươi và sốt đặc biệt",
                            ImageUrl = "https://burgerking.vn/media/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/1/7/17-whopper-b_-t_m-ph_-mai-c_-l_n.jpg",
                            IsActive = true,
                            Name = "Burger Bò Phô Mai",
                            Price = 55000m,
                            Tag = "bò, phô mai, burger"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Burger gà rán giòn với sốt mayonnaise và rau tươi",
                            ImageUrl = "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=500",
                            IsActive = true,
                            Name = "Burger Gà Giòn",
                            Price = 50000m,
                            Tag = "gà, burger, giòn"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Miếng gà rán giòn rụm với công thức bí mật 11 loại gia vị",
                            ImageUrl = "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500",
                            IsActive = true,
                            Name = "Gà Rán Giòn Truyền Thống",
                            Price = 45000m,
                            Tag = "gà, rán, giòn"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Gà rán cay nồng với ớt và tiêu đen",
                            ImageUrl = "https://images.unsplash.com/photo-1594221708779-94832f4320d1?w=500",
                            IsActive = true,
                            Name = "Gà Rán Cay",
                            Price = 47000m,
                            Tag = "gà, cay, rán"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Cánh gà chiên giòn sốt nước mắm đậm đà",
                            ImageUrl = "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=500",
                            IsActive = true,
                            Name = "Cánh Gà Chiên Nước Mắm",
                            Price = 40000m,
                            Tag = "gà, cánh, chiên"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Nước ngọt có gas Coca Cola classic",
                            ImageUrl = "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500",
                            IsActive = true,
                            Name = "Coca Cola",
                            Price = 20000m,
                            Tag = "nước ngọt, coca, gas"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Nước ngọt có gas Pepsi",
                            ImageUrl = "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=500",
                            IsActive = true,
                            Name = "Pepsi",
                            Price = 20000m,
                            Tag = "nước ngọt, pepsi, gas"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Trà sữa ngọt ngào với trân châu đen dai",
                            ImageUrl = "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=500",
                            IsActive = true,
                            Name = "Trà Sữa Trân Châu",
                            Price = 35000m,
                            Tag = "trà sữa, trân châu, ngọt"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Nước cam tươi ép 100%",
                            ImageUrl = "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500",
                            IsActive = true,
                            Name = "Nước Cam Ép",
                            Price = 30000m,
                            Tag = "nước ép, cam, tươi"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Khoai tây chiên giòn vàng ươm",
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500",
                            IsActive = true,
                            Name = "Khoai Tây Chiên",
                            Price = 30000m,
                            Tag = "khoai tây, chiên, snack"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Salad rau củ tươi với sốt mayonnaise",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
                            IsActive = true,
                            Name = "Salad Rau Củ",
                            Price = 35000m,
                            Tag = "salad, rau, healthy"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Kem vani béo ngậy mát lạnh",
                            ImageUrl = "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500",
                            IsActive = true,
                            Name = "Kem Vani",
                            Price = 25000m,
                            Tag = "kem, vani, ngọt"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Bánh táo nướng thơm giòn",
                            ImageUrl = "https://images.unsplash.com/photo-1562007908-17c67e878c88?w=500",
                            IsActive = true,
                            Name = "Bánh Táo",
                            Price = 28000m,
                            Tag = "bánh, táo, nướng"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Burger tôm tươi giòn tan với sốt cocktail đặc biệt",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsActive = true,
                            Name = "Burger Tôm",
                            Price = 65000m,
                            Tag = "tôm, burger, hải sản"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Burger gà với sốt teriyaki Nhật Bản, dứa nướng",
                            ImageUrl = "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
                            IsActive = true,
                            Name = "Burger Gà Teriyaki",
                            Price = 58000m,
                            Tag = "gà, teriyaki, burger"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Hai lớp thịt bò 100% với phô mai cheddar tan chảy",
                            ImageUrl = "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500",
                            IsActive = true,
                            Name = "Burger Bò Phô Mai Đôi",
                            Price = 75000m,
                            Tag = "bò, phô mai, burger, double"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Burger chay từ đậu và rau củ, phù hợp người ăn chay",
                            ImageUrl = "https://images.unsplash.com/photo-1520072959219-c595dc870360?w=500",
                            IsActive = true,
                            Name = "Burger Chay",
                            Price = 52000m,
                            Tag = "chay, burger, healthy"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Gà rán giòn phủ sốt BBQ ngọt cay đậm đà",
                            ImageUrl = "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500",
                            IsActive = true,
                            Name = "Gà Rán Sốt BBQ",
                            Price = 48000m,
                            Tag = "gà, bbq, rán"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Phi lê gà rán không xương, dễ ăn",
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=500",
                            IsActive = true,
                            Name = "Gà Phi Lê",
                            Price = 46000m,
                            Tag = "gà, phi lê, rán"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Nước ngọt có gas Sprite chanh mát lạnh",
                            ImageUrl = "https://images.unsplash.com/photo-1625772452859-1c03d5bf1137?w=500",
                            IsActive = true,
                            Name = "Sprite",
                            Price = 20000m,
                            Tag = "nước ngọt, sprite, gas"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Trà đào kết hợp cam sả thơm mát",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500",
                            IsActive = true,
                            Name = "Trà Đào Cam Sả",
                            Price = 38000m,
                            Tag = "trà, đào, cam sả"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Sinh tố bơ béo ngậy, bổ dưỡng",
                            ImageUrl = "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=500",
                            IsActive = true,
                            Name = "Sinh Tố Bơ",
                            Price = 40000m,
                            Tag = "sinh tố, bơ, healthy"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Cà phê đen đá truyền thống Việt Nam",
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500",
                            IsActive = true,
                            Name = "Cà Phê Đen",
                            Price = 25000m,
                            Tag = "cà phê, đen, việt nam"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Cà phê sữa đá ngọt ngào",
                            ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500",
                            IsActive = true,
                            Name = "Cà Phê Sữa",
                            Price = 28000m,
                            Tag = "cà phê, sữa, việt nam"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "Gỏi cuốn tôm tươi với rau sống và bún",
                            ImageUrl = "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=500",
                            IsActive = true,
                            Name = "Gỏi Cuốn Tôm",
                            Price = 32000m,
                            Tag = "gỏi cuốn, tôm, healthy"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Salad caesar với gà nướng và sốt đặc biệt",
                            ImageUrl = "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500",
                            IsActive = true,
                            Name = "Salad Caesar",
                            Price = 42000m,
                            Tag = "salad, caesar, gà"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Kem chocolate đậm đà, ngọt ngào",
                            ImageUrl = "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500",
                            IsActive = true,
                            Name = "Kem Chocolate",
                            Price = 25000m,
                            Tag = "kem, chocolate, ngọt"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Kem dâu tươi mát lạnh",
                            ImageUrl = "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=500",
                            IsActive = true,
                            Name = "Kem Dâu",
                            Price = 25000m,
                            Tag = "kem, dâu, ngọt"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Description = "Bánh flan caramel mềm mịn",
                            ImageUrl = "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=500",
                            IsActive = true,
                            Name = "Bánh Flan",
                            Price = 22000m,
                            Tag = "flan, caramel, ngọt"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Description = "Brownie chocolate đắng ngọt, nóng giòn",
                            ImageUrl = "https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=500",
                            IsActive = true,
                            Name = "Brownie Chocolate",
                            Price = 32000m,
                            Tag = "brownie, chocolate, bánh"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 5,
                            Description = "Kem vani phủ sốt caramel và hạt",
                            ImageUrl = "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500",
                            IsActive = true,
                            Name = "Sundae Caramel",
                            Price = 30000m,
                            Tag = "kem, sundae, caramel"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            Description = "Burger bò với bacon giòn, phô mai và sốt BBQ",
                            ImageUrl = "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=500",
                            IsActive = true,
                            Name = "Burger Bò Bacon",
                            Price = 68000m,
                            Tag = "bò, bacon, burger"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Burger gà rán cay kiểu Hàn với sốt gochujang",
                            ImageUrl = "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500",
                            IsActive = true,
                            Name = "Burger Gà Cay Hàn Quốc",
                            Price = 62000m,
                            Tag = "gà, cay, hàn quốc"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            Description = "Burger phô mai nướng giòn tan với nhiều loại phô mai",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsActive = true,
                            Name = "Burger Phô Mai Nướng",
                            Price = 55000m,
                            Tag = "phô mai, burger, nướng"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Description = "Gà rán phủ lớp phô mai tan chảy bên trong",
                            ImageUrl = "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=500",
                            IsActive = true,
                            Name = "Gà Rán Phô Mai",
                            Price = 52000m,
                            Tag = "gà, phô mai, rán"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Cánh gà cay kiểu Mỹ với sốt buffalo",
                            ImageUrl = "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=500",
                            IsActive = true,
                            Name = "Cánh Gà Buffalo",
                            Price = 45000m,
                            Tag = "gà, cánh, buffalo"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            Description = "Gà viên chiên giòn dạng nuggets cho trẻ em",
                            ImageUrl = "https://images.unsplash.com/photo-1562967914-608f82629710?w=500",
                            IsActive = true,
                            Name = "Gà Nuggets",
                            Price = 38000m,
                            Tag = "gà, nuggets, trẻ em"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "Trà sữa matcha Nhật Bản với trân châu trắng",
                            ImageUrl = "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=500",
                            IsActive = true,
                            Name = "Trà Sữa Matcha",
                            Price = 42000m,
                            Tag = "trà sữa, matcha, nhật bản"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            Description = "Sinh tố xoài tươi ngọt mát",
                            ImageUrl = "https://images.unsplash.com/photo-1546173159-315724a31696?w=500",
                            IsActive = true,
                            Name = "Sinh Tố Xoài",
                            Price = 38000m,
                            Tag = "sinh tố, xoài, tươi"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Description = "Soda chanh dây tươi mát giải nhiệt",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500",
                            IsActive = true,
                            Name = "Soda Chanh Dây",
                            Price = 32000m,
                            Tag = "soda, chanh dây, tươi"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "Trà chanh tươi mát lạnh giải khát",
                            ImageUrl = "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500",
                            IsActive = true,
                            Name = "Trà Chanh",
                            Price = 28000m,
                            Tag = "trà, chanh, giải khát"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "Hành tây tẩm bột chiên giòn giòn với sốt",
                            ImageUrl = "https://images.unsplash.com/photo-1639024471283-03518883512d?w=500",
                            IsActive = true,
                            Name = "Hành Tây Chiên Giòn",
                            Price = 35000m,
                            Tag = "hành tây, chiên, snack"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "Phô mai que tẩm bột chiên giòn tan",
                            ImageUrl = "https://images.unsplash.com/photo-1548340748-6d2b7d7da280?w=500",
                            IsActive = true,
                            Name = "Phô Mai Que Chiên",
                            Price = 40000m,
                            Tag = "phô mai, chiên, que"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "Salad rau củ tươi trộn dầu giấm balsamic",
                            ImageUrl = "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500",
                            IsActive = true,
                            Name = "Salad Trộn Dầu Giấm",
                            Price = 38000m,
                            Tag = "salad, rau, healthy"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Description = "Bánh donut phủ socola và rắc hạt",
                            ImageUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500",
                            IsActive = true,
                            Name = "Bánh Donut Socola",
                            Price = 26000m,
                            Tag = "donut, socola, bánh"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            Description = "Tiramisu Ý truyền thống với cà phê và mascarpone",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500",
                            IsActive = true,
                            Name = "Tiramisu",
                            Price = 45000m,
                            Tag = "tiramisu, cà phê, ý"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            Description = "Kem matcha Nhật Bản đắng ngọt hài hòa",
                            ImageUrl = "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500",
                            IsActive = true,
                            Name = "Kem Matcha",
                            Price = 28000m,
                            Tag = "kem, matcha, nhật bản"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            Description = "Pudding xoài mềm mịn béo ngậy",
                            ImageUrl = "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500",
                            IsActive = true,
                            Name = "Pudding Xoài",
                            Price = 30000m,
                            Tag = "pudding, xoài, ngọt"
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại burger bò, gà, cá",
                            Name = "Burger"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các món gà rán giòn, cay",
                            Name = "Gà rán"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nước ngọt, trà sữa, nước ép",
                            Name = "Đồ uống"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Khoai tây, salad, snack",
                            Name = "Món phụ"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kem, bánh ngọt",
                            Name = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FastFoodOnline.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("FoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị hệ thống",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Khách hàng",
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("FastFoodOnline.Models.Account", b =>
                {
                    b.HasOne("FastFoodOnline.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FastFoodOnline.Models.ComboItem", b =>
                {
                    b.HasOne("FastFoodOnline.Models.Combo", "Combo")
                        .WithMany("Items")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodOnline.Models.Food", "Food")
                        .WithMany("ComboItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Food", b =>
                {
                    b.HasOne("FastFoodOnline.Models.FoodCategory", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Order", b =>
                {
                    b.HasOne("FastFoodOnline.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FastFoodOnline.Models.OrderDetail", b =>
                {
                    b.HasOne("FastFoodOnline.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("FastFoodOnline.Models.Food", "Food")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FoodId");

                    b.HasOne("FastFoodOnline.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Combo", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Food", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("FastFoodOnline.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FastFoodOnline.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
